framework:
  messenger:
    default_bus: messenger.bus.events

    transports:
      commands: enqueue://commands
      events: enqueue://events

    buses:
      messenger.bus.commands:
        middleware: ~

      messenger.bus.events:
        middleware:
        - Mercur\Bundle\MessagingBundle\Middleware\TolerateNoHandler
